language: node_js

node_js:
  - "node"

addons:
  code_climate:
    repo_token:
      secure: "1cad8483e05f9dd48535e678ceea1b6e33034228fd804b0f4278e9f3e69d221e"

env:
  - NODE_ENV=TEST
  - ENV_TYPE=TEST

script:
  - npm run test

before_script:
  - npm run migrate-down
  - npm run migrate-up
  # - npm run insert-admin
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# after_success: npm run coverage
